## Default loading point for bash customizations

## Load other files
if [ -f ~/.my_bash_aliases ]; then
	source ~/.my_bash_aliases
fi
if [ -f ~/.my_bash_functions ]; then
    source ~/.my_bash_functions
fi
if [ -f ~/.my_bash_prompt ]; then
    source ~/.my_bash_prompt
fi

export PATH="$PATH:/opt/node/bin"

PROXY_REQUIRED=1
if [[ PROXY_REQUIRED -eq 1 ]]; then
    proxy
else 
    unproxy
fi

