# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Configure Brew if in local dir
HB="$HOME/.homebrew/bin"
if [ -d $HB ] ; then
    PATH=$PATH:$HB
fi

export ZSH=$HOME/.oh-my-zsh
ZSH_CUSTOM=$HOME/.zsh_custom
ZSH_THEME="powerlevel10k/powerlevel10k" 
COMPLETION_WAITING_DOTS="true"
plugins=(
  git
  git-extras
  gitignore
  wd
)

ZSH_LOCAL="$ZSH/oh-my-zsh.sh"
if [ -d $ZSH_LOCAL ] ; then
    source $ZSH_LOCAL
fi

# My loading point
if [ -f ~/.zsh/my_zshrc ]; then
    . ~/.zsh/my_zshrc
fi

#eval "$(starship init zsh)"
source /Users/tbennett/.homebrew/opt/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
